export const SEED = {
  customers: [
    {
      id: "c1",
      name: "Akua Mensah",
      phone: "0241000001",
      email: "akua@email.com",
      location: "Kumasi",
      totalOrders: 9,
      ltv: 495,
      lastPurchase: "2025-03-25",
      favSku: "GEL-TP-WTML",
      segment: "High-Value",
      joinDate: "2025-01-10",
      source: "Instagram",
      notes: "Loves watermelon range",
    },
    {
      id: "c2",
      name: "Kwame Boateng",
      phone: "0201000002",
      email: "",
      location: "Accra",
      totalOrders: 3,
      ltv: 66,
      lastPurchase: "2025-03-23",
      favSku: "GEL-TP-MINT",
      segment: "Repeat",
      joinDate: "2025-02-05",
      source: "WhatsApp",
      notes: "",
    },
    {
      id: "c3",
      name: "Abena Asare",
      phone: "0271000003",
      email: "abena@gmail.com",
      location: "Tema",
      totalOrders: 1,
      ltv: 22,
      lastPurchase: "2025-03-24",
      favSku: "GEL-TP-WTML",
      segment: "New",
      joinDate: "2025-03-24",
      source: "TikTok",
      notes: "Promo convert",
    },
    {
      id: "c4",
      name: "Yaw Darko",
      phone: "0551000004",
      email: "",
      location: "Takoradi",
      totalOrders: 5,
      ltv: 175,
      lastPurchase: "2024-12-10",
      favSku: "GEL-FL-001",
      segment: "Churn Risk",
      joinDate: "2024-10-01",
      source: "Referral",
      notes: "Inactive 90+ days",
    },
    {
      id: "c5",
      name: "Ama Owusu",
      phone: "0241000005",
      email: "ama@email.com",
      location: "Kumasi",
      totalOrders: 6,
      ltv: 210,
      lastPurchase: "2025-03-26",
      favSku: "GEL-WK-001",
      segment: "High-Value",
      joinDate: "2025-01-22",
      source: "Instagram",
      notes: "",
    },
  ],
  orders: [
    {
      id: "ORD-001",
      customerId: "c1",
      customerName: "Akua Mensah",
      items: [
        { sku: "GEL-TP-WTML", qty: 2 },
        { sku: "GEL-FL-001", qty: 1 },
      ],
      value: 79,
      paymentMethod: "Mobile Money",
      status: "Delivered",
      source: "Instagram",
      campaignId: "CAM-001",
      date: "2025-03-22",
      notes: "",
    },
    {
      id: "ORD-002",
      customerId: "c2",
      customerName: "Kwame Boateng",
      items: [{ sku: "GEL-TP-MINT", qty: 2 }],
      value: 40,
      paymentMethod: "Cash",
      status: "Delivered",
      source: "WhatsApp",
      campaignId: "",
      date: "2025-03-23",
      notes: "",
    },
    {
      id: "ORD-003",
      customerId: "c3",
      customerName: "Abena Asare",
      items: [{ sku: "GEL-TP-WTML", qty: 1 }],
      value: 22,
      paymentMethod: "Mobile Money",
      status: "Delivered",
      source: "TikTok",
      campaignId: "CAM-002",
      date: "2025-03-24",
      notes: "First buy via promo",
    },
    {
      id: "ORD-004",
      customerId: "c5",
      customerName: "Ama Owusu",
      items: [
        { sku: "GEL-WK-001", qty: 1 },
        { sku: "GEL-MB-001", qty: 1 },
      ],
      value: 113,
      paymentMethod: "Card",
      status: "Delivered",
      source: "Instagram",
      campaignId: "CAM-001",
      date: "2025-03-25",
      notes: "Bundle",
    },
    {
      id: "ORD-005",
      customerId: "c1",
      customerName: "Akua Mensah",
      items: [{ sku: "GEL-TP-WTML", qty: 3 }],
      value: 66,
      paymentMethod: "Mobile Money",
      status: "Processing",
      source: "Instagram",
      campaignId: "CAM-001",
      date: "2025-03-27",
      notes: "",
    },
    {
      id: "ORD-006",
      customerId: "c2",
      customerName: "Kwame Boateng",
      items: [{ sku: "GEL-FL-001", qty: 1 }],
      value: 35,
      paymentMethod: "COD",
      status: "Failed",
      source: "WhatsApp",
      campaignId: "",
      date: "2025-03-27",
      notes: "COD refused",
    },
  ],
  dtcInventory: [
    { sku: "GEL-TP-WTML", stock: 42, reorder: 30, velocity: 4.2 },
    { sku: "GEL-TP-MINT", stock: 88, reorder: 30, velocity: 2.1 },
    { sku: "GEL-TP-CHAR", stock: 25, reorder: 30, velocity: 1.8 },
    { sku: "GEL-FL-001", stock: 19, reorder: 20, velocity: 1.4 },
    { sku: "GEL-WK-001", stock: 11, reorder: 15, velocity: 0.9 },
    { sku: "GEL-MB-001", stock: 60, reorder: 25, velocity: 1.2 },
  ],
  campaigns: [
    {
      id: "CAM-001",
      name: "IG Spring Launch",
      channel: "Instagram",
      spend: 1200,
      startDate: "2025-03-15",
      endDate: "2025-03-31",
      status: "Active",
    },
    {
      id: "CAM-002",
      name: "TikTok Oral Care",
      channel: "TikTok",
      spend: 800,
      startDate: "2025-03-20",
      endDate: "2025-04-05",
      status: "Active",
    },
    {
      id: "CAM-003",
      name: "WhatsApp Flash Sale",
      channel: "WhatsApp",
      spend: 200,
      startDate: "2025-03-10",
      endDate: "2025-03-12",
      status: "Ended",
    },
  ],
  outlets: [
    {
      id: "o1",
      name: "Accra Mart",
      channel: "Modern Trade",
      location: "Accra Central",
      contact: "0241234567",
      status: "Active",
      rep: "Kofi Mensah",
      date: "2025-03-10",
      notes: "High volume",
    },
    {
      id: "o2",
      name: "Kwame Stores",
      channel: "General Trade",
      location: "Kumasi",
      contact: "0551234567",
      status: "Active",
      rep: "Ama Owusu",
      date: "2025-03-12",
      notes: "",
    },
    {
      id: "o3",
      name: "Coast Wholesale",
      channel: "Wholesale",
      location: "Takoradi",
      contact: "0201234567",
      status: "Pending",
      rep: "Kweku Asante",
      date: "2025-03-15",
      notes: "Awaiting samples",
    },
    {
      id: "o4",
      name: "Unity Superstore",
      channel: "Modern Trade",
      location: "East Legon",
      contact: "0271234567",
      status: "Active",
      rep: "Abena Darko",
      date: "2025-03-18",
      notes: "",
    },
    {
      id: "o5",
      name: "Nana Traders",
      channel: "General Trade",
      location: "Tema",
      contact: "0241113344",
      status: "Follow-up",
      rep: "Yaw Boateng",
      date: "2025-03-20",
      notes: "Bulk deal interest",
    },
  ],
  visits: [
    {
      id: "v1",
      outlet: "Accra Mart",
      rep: "Kofi Mensah",
      date: "2025-03-22",
      purpose: "Routine",
      outcome: "Order placed GHS 4800",
      followup: "Deliver next week",
      status: "Completed",
    },
    {
      id: "v2",
      outlet: "Kwame Stores",
      rep: "Ama Owusu",
      date: "2025-03-23",
      purpose: "POSM Placement",
      outcome: "Placed 3 banners",
      followup: "None",
      status: "Completed",
    },
    {
      id: "v3",
      outlet: "Coast Wholesale",
      rep: "Kweku Asante",
      date: "2025-03-24",
      purpose: "New Listing",
      outcome: "Interested",
      followup: "Send samples",
      status: "Follow-up",
    },
    {
      id: "v4",
      outlet: "Unity Superstore",
      rep: "Abena Darko",
      date: "2025-03-25",
      purpose: "Payment Collection",
      outcome: "GHS 2400 collected",
      followup: "None",
      status: "Completed",
    },
    {
      id: "v5",
      outlet: "Nana Traders",
      rep: "Yaw Boateng",
      date: "2025-03-26",
      purpose: "Routine",
      outcome: "Low stock noted",
      followup: "Replenish",
      status: "Pending",
    },
  ],
  posm: [
    { id: "p1", type: "Banner", outlet: "Accra Mart", qty: 4, rep: "Kofi Mensah", date: "2025-03-22", status: "Deployed" },
    { id: "p2", type: "Shelf Talker", outlet: "Kwame Stores", qty: 10, rep: "Ama Owusu", date: "2025-03-23", status: "Deployed" },
    { id: "p3", type: "Wobbler", outlet: "Unity Superstore", qty: 6, rep: "Abena Darko", date: "2025-03-25", status: "Deployed" },
    { id: "p4", type: "Poster", outlet: "Coast Wholesale", qty: 2, rep: "Kweku Asante", date: "2025-03-24", status: "Pending" },
  ],
  sfInventory: [
    { id: "i1", product: "Gelos Classic 500ml", sku: "GCL500", stock: 340, reorder: 100, unit: "Cases", rep: "Kofi Mensah", updated: "2025-03-25" },
    { id: "i2", product: "Gelos Gold 1L", sku: "GGL1L", stock: 80, reorder: 100, unit: "Cases", rep: "Ama Owusu", updated: "2025-03-24" },
    { id: "i3", product: "Gelos Fresh 250ml", sku: "GFR250", stock: 15, reorder: 50, unit: "Cases", rep: "Kweku Asante", updated: "2025-03-26" },
    { id: "i4", product: "Gelos Premium 2L", sku: "GPR2L", stock: 200, reorder: 80, unit: "Cases", rep: "Abena Darko", updated: "2025-03-23" },
    { id: "i5", product: "Gelos Lite 330ml", sku: "GLT330", stock: 45, reorder: 60, unit: "Cases", rep: "Yaw Boateng", updated: "2025-03-25" },
  ],
  b2bPayments: [
    { id: "py1", outlet: "Accra Mart", invoice: "INV-001", amount: 4800, paid: 4800, date: "2025-03-20", due: "2025-03-27", status: "Paid", rep: "Kofi Mensah" },
    { id: "py2", outlet: "Kwame Stores", invoice: "INV-002", amount: 2200, paid: 0, date: "2025-03-18", due: "2025-03-25", status: "Overdue", rep: "Ama Owusu" },
    { id: "py3", outlet: "Coast Wholesale", invoice: "INV-003", amount: 7500, paid: 3000, date: "2025-03-22", due: "2025-03-29", status: "Partial", rep: "Kweku Asante" },
    { id: "py4", outlet: "Unity Superstore", invoice: "INV-004", amount: 5100, paid: 5100, date: "2025-03-23", due: "2025-03-30", status: "Paid", rep: "Abena Darko" },
    { id: "py5", outlet: "Nana Traders", invoice: "INV-005", amount: 1800, paid: 0, date: "2025-03-24", due: "2025-03-31", status: "Pending", rep: "Yaw Boateng" },
  ],
  targets: [
    { id: "t1", rep: "Kofi Mensah", monthlyTarget: 15000, visitsTarget: 25, ordersTarget: 18, achieved: 4800 },
    { id: "t2", rep: "Ama Owusu", monthlyTarget: 12000, visitsTarget: 22, ordersTarget: 15, achieved: 0 },
    { id: "t3", rep: "Kweku Asante", monthlyTarget: 18000, visitsTarget: 28, ordersTarget: 20, achieved: 3000 },
    { id: "t4", rep: "Abena Darko", monthlyTarget: 14000, visitsTarget: 24, ordersTarget: 17, achieved: 5100 },
    { id: "t5", rep: "Yaw Boateng", monthlyTarget: 10000, visitsTarget: 20, ordersTarget: 12, achieved: 0 },
  ],
};

