import type { CSSProperties } from "react";
import { C } from "./constants";

const css = (s: CSSProperties) => s;

export const S = {
  app: css({
    display: "flex",
    height: "100%",
    minHeight: 0,
    maxHeight: "100%",
    overflow: "hidden",
    fontFamily: "'Segoe UI',system-ui,sans-serif",
    background: "#f0f4f8",
    color: "#222",
  }),
  sidebar: css({
    width: 258,
    height: "100%",
    minHeight: 0,
    background: "#000",
    color: "#fff",
    display: "flex",
    flexDirection: "column",
    flexShrink: 0,
    overflow: "hidden",
    borderRight: "1px solid rgba(255,255,255,.08)",
  }),
  sidebarNav: css({
    flex: 1,
    minHeight: 0,
    overflowY: "auto",
    padding: "6px 0",
  }),
  brand: css({ padding: "20px 20px 14px", borderBottom: "1px solid rgba(255,255,255,.1)" }),
  brandH: css({
    fontSize: "1.45rem",
    fontWeight: 900,
    letterSpacing: 2,
    color: "#fff",
    margin: 0,
  }),
  brandP: css({ fontSize: ".68rem", opacity: 0.5, marginTop: 4, letterSpacing: 1.2, color: "rgba(255,255,255,.85)" }),
  navSection: (c?: string) =>
    css({
      padding: "12px 20px 6px",
      fontSize: ".68rem",
      fontWeight: 700,
      letterSpacing: 1.6,
      color: c || "rgba(255,255,255,.38)",
      textTransform: "uppercase",
      marginTop: 6,
    }),
  navA: (a?: boolean, c?: string) =>
    css({
      display: "flex",
      alignItems: "center",
      gap: 11,
      padding: "11px 20px",
      fontSize: ".92rem",
      cursor: "pointer",
      color: a ? "#fff" : "rgba(255,255,255,.68)",
      background: a ? "rgba(255,255,255,.09)" : "transparent",
      borderLeft: a ? `3px solid ${c || C.accent}` : "3px solid transparent",
      transition: "background .15s, color .15s, border-color .15s",
    }),
  main: css({ flex: 1, minHeight: 0, display: "flex", flexDirection: "column", overflow: "hidden" }),
  topbar: css({
    flexShrink: 0,
    background: "#fff",
    borderBottom: "1px solid #dde3ea",
    padding: "14px 26px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 8,
  }),
  content: css({ flex: 1, minHeight: 0, overflowY: "auto", padding: "22px 26px", WebkitOverflowScrolling: "touch" }),
  card: css({
    background: "#fff",
    borderRadius: 12,
    boxShadow: "0 2px 10px rgba(0,0,0,.08)",
    overflow: "hidden",
    marginBottom: 18,
  }),
  cardHeader: (c?: string) =>
    css({
      padding: "14px 18px",
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      borderBottom: "1px solid #eee",
      borderLeft: `3px solid ${c || C.primary}`,
    }),
  statGrid: css({ display: "grid", gridTemplateColumns: "repeat(auto-fill,minmax(168px,1fr))", gap: 14, marginBottom: 18 }),
  statCard: (c?: string) =>
    css({
      background: "#fff",
      borderRadius: 12,
      padding: "15px 17px",
      boxShadow: "0 2px 10px rgba(0,0,0,.08)",
      borderTop: `3px solid ${c || C.primary}`,
    }),
  table: css({ width: "100%", borderCollapse: "collapse", fontSize: ".88rem" }),
  th: css({
    background: "#f7f9fb",
    padding: "10px 13px",
    textAlign: "left",
    fontSize: ".8rem",
    color: "#888",
    fontWeight: 700,
    borderBottom: "1px solid #eee",
  }),
  td: css({ padding: "9px 13px", borderBottom: "1px solid #f5f5f5", verticalAlign: "middle" }),
  btn: (col?: string, bg?: string) =>
    css({
      padding: "8px 16px",
      border: "none",
      borderRadius: 8,
      fontSize: ".88rem",
      cursor: "pointer",
      fontWeight: 700,
      color: col || "#fff",
      background: bg || C.primary,
    }),
  btnSm: (bg?: string) =>
    css({
      padding: "5px 11px",
      border: "none",
      borderRadius: 6,
      fontSize: ".82rem",
      cursor: "pointer",
      fontWeight: 700,
      color: "#fff",
      background: bg || C.primary,
    }),
  input: css({
    padding: "9px 12px",
    border: "1px solid #dde3ea",
    borderRadius: 8,
    fontSize: ".92rem",
    width: "100%",
    boxSizing: "border-box",
  }),
  select: css({
    padding: "9px 12px",
    border: "1px solid #dde3ea",
    borderRadius: 8,
    fontSize: ".92rem",
    background: "#fff",
  }),
  overlay: css({
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,.5)",
    zIndex: 300,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  }),
  modal: css({ background: "#fff", borderRadius: 14, padding: 28, width: 620, maxWidth: "96vw", maxHeight: "90vh", overflowY: "auto" }),
  badge: (c?: string, bg?: string) =>
    css({
      display: "inline-block",
      padding: "3px 10px",
      borderRadius: 20,
      fontSize: ".76rem",
      fontWeight: 700,
      color: c || "#555",
      background: bg || "#eee",
    }),
  alert: (c: string) =>
    css({
      background: "#fff",
      borderLeft: `4px solid ${c}`,
      padding: "11px 15px",
      borderRadius: 8,
      fontSize: ".9rem",
      boxShadow: "0 1px 4px rgba(0,0,0,.06)",
      marginBottom: 7,
    }),
  aiBox: css({
    background: "#f0f7ff",
    border: "1px solid #b8d4f8",
    borderRadius: 12,
    padding: 16,
    marginTop: 12,
    fontSize: ".92rem",
    lineHeight: 1.65,
    whiteSpace: "pre-wrap",
  }),
  formGrid: css({ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 13 }),
  fg: (full?: boolean) => css({ display: "flex", flexDirection: "column", gap: 4, gridColumn: full ? "1/-1" : "auto" }),
  label: css({ fontSize: ".8rem", color: "#888", fontWeight: 700 }),
  secLabel: (c?: string) =>
    css({ fontSize: ".82rem", fontWeight: 700, color: c || "#888", letterSpacing: 0.7, marginBottom: 8, marginTop: 16 }),
  medal: ["#e8a020", "#888", "#cd7f32", "#aaa"],
} as const;

